spring.application.name=finance-tracker

server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://tokaido.proxy.rlwy.net:57299/railway
spring.datasource.username=root
spring.datasource.password=FopuqpbFbrMNzcRSoebjbAjmFmgSfLUX

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true